<a href="https://colab.research.google.com/github/Arprovat/Python__B-2__EDGE/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
## Why use Numpy?
 Python is not memory efficient to store numbers since it wraps everything into objects. Whereas in NumPy, we can select the number of bits to represent numbers.Numpy provide a effecient storage.It uses reletivly less space in memory to store data .It gives better way to handle data(Numaric) for processing .It fast and easy to learn.

## Array in Numpy
Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
### Create Array in Numpy
lets see ...


**Create array using python data type.**

In [1]:
import numpy as np

Array = np.array([2,3,4,5,8,6,7]) #rank 1 array

In [2]:
Array

array([2, 3, 4, 5, 8, 6, 7])

In [3]:

Array = np.array([[2,3,4,5,8,6,7],
                 [0,9,8,7,6,5,3]]) #rank 2 array
Array                              #number of element in 1st and 2nd rank must equal

array([[2, 3, 4, 5, 8, 6, 7],
       [0, 9, 8, 7, 6, 5, 3]])

In [4]:
#create Numpy array using tuple
Array = np.array((1,3,4,5,8,6,7))
Array

array([1, 3, 4, 5, 8, 6, 7])

**Create array using Function**

In [5]:
arrayZero = np.zeros((2,3))# create a Array full of zeros
arrayZero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arrayArange= np.arange(99)
arrayArange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [7]:
arrayArange = arrayArange.reshape(3,33)#Make shpae like (no of row ,no. of element)
arrayArange

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [9]:
arrayArange = arrayArange.ravel()# make 1D array
arrayArange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [10]:
arrayArange = np.arange(1,100,2)#(start,stop,step)
arrayArange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
ArrayIndetity = np.identity(5)#create identity matrix
ArrayIndetity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arrayArange.shape

(50,)

In [23]:
ArrayIndetity.shape

(5, 5)

### Accessing Data in Array

In [11]:
Array[0]

1

In [12]:
Array=np.array([[1,23,4,5,654]])
Array[0,1]


23

In [13]:
#Slice
Array=np.array([1,23,4,5,654])
Array[:2]

array([ 1, 23])

In [14]:
Array = np.array([[2,3,4,5,8,6,7],
                 [0,9,8,7,6,5,3]])
Array[:2,:2]

array([[2, 3],
       [0, 9]])

## What Are Axes?
Imagine a NumPy array like a multi-dimensional grid. Axes are simply the directions you can move along this grid. Think of them like the x, y, and z coordinates in a 3D space.

**Decoding**

axis=x

The axis argument in NumPy functions specifies which axis to perform the operation along. Here's how it translates for different array dimensions:

**1D Array (axis=0):**

The only axis available. Operations will apply across all elements of the array.

**2D Array:**

axis=0: Operates along rows (vertically). For example, np.sum(arr_2d, axis=0) calculates the sum of each column.

axis=1: Operates along columns (horizontally). np.sum(arr_2d, axis=1) calculates the sum of each row.

**3D Array:**

axis=0: Operates along the depth (the outermost dimension). Each operation is applied to the 2D arrays stacked along this axis.

axis=1: Operates along rows within each depth level.

axis=2: Operates along columns within each depth level.

In [25]:
#1D array
arr_ = np.array([1, 2, 3, 4, 5])
print(arr_)
print(arr_.sum(axis=0))

[1 2 3 4 5]
15


In [29]:
#2d Array
arr_ = np.array([[3,5,6,7],
                [6,7,8,9],
                [5,3,4,2]])
print(arr_.sum(axis=0))#sum(3+6+5)/Row
print(arr_.sum(axis=1))#Sum(3+5+6+7)/coloum

[14 15 18 18]
[21 30 14]


In [33]:
#3d Array
arr_3D = np.array([[[3,5,6,7],[6,7,4,5]],
                  [[5,6,7,8],[2,4,5,6]]])

print(arr_3D.sum(axis=0))
print(arr_3D.sum(axis=1))
print(arr_3D.sum(axis=2))

[[ 8 11 13 15]
 [ 8 11  9 11]]
[[ 9 12 10 12]
 [ 7 10 12 14]]
[[21 22]
 [26 17]]
